version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Debug
  - GENERATOR: '"MSYS Makefiles"'
    BUILD_TYPE: Release
  - GENERATOR: '"Visual Studio 14 2015"'
    BUILD_TYPE: Debug
  - GENERATOR: '"Visual Studio 14 2015"'
    BUILD_TYPE: Release
  - GENERATOR: '"Visual Studio 14 2015 Win64"'
    BUILD_TYPE: Debug
  - GENERATOR: '"Visual Studio 14 2015 Win64"'
    BUILD_TYPE: Release
  - GENERATOR: '"Visual Studio 15 2017 Win64"'
    BUILD_TYPE: Debug
  - GENERATOR: '"Visual Studio 15 2017 Win64"'
    BUILD_TYPE: Release
build_script:
- cmd: >-
    set
    
    mkdir build
    
    cd build 

    set PATH=%PATH%:C:\Program Files\Git\usr\bin

    set PATH=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw32\bin;C:\msys64\usr\bin;%PATH% 
    
    cmake .. -G %GENERATOR% -D_WIN32 -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DSPDLOG_WCHAR_SUPPORT=ON -DSPDLOG_BUILD_EXAMPLE=ON -DSPDLOG_BUILD_EXAMPLE_HO=ON -DSPDLOG_BUILD_TESTS=ON -DSPDLOG_BUILD_TESTS_HO=OFF

    cmake --build . --config %BUILD_TYPE%

test_script:
- ctest -VV -C "%BUILD_TYPE%"
